In [3]:
import pandas as pd

d = {
    "sales": [
        100000,
        222000,
        1000000,
        522000,
        111111,
        222222,
        1111111,
        20000
    ],
    "city": [
        "Tampa",
        "Tampa",
        "Orlando",
        "Jacksonville",
        "Miami",
        "Jacksonville",
        "Miami",
        "Miami"
    ],
    "size": [
        "Small",
        "Medium",
        "Large",
        "Large",
        "Small",
        "Medium",
        "Large",
        "Small"
    ]
}

In [4]:
df = pd.DataFrame(d)
df

     sales          city    size
0   100000         Tampa   Small
1   222000         Tampa  Medium
2  1000000       Orlando   Large
3   522000  Jacksonville   Large
4   111111         Miami   Small
5   222222  Jacksonville  Medium
6  1111111         Miami   Large
7    20000         Miami   Small

In [5]:
df['size'].unique()

array(['Small', 'Medium', 'Large'], dtype=object)

In [6]:
sizes=['Small', 'Medium', 'Large']

In [7]:
from sklearn.preprocessing import OrdinalEncoder

In [12]:
enc = OrdinalEncoder(categories=[sizes])

In [13]:
enc.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.]])

In [14]:
df.size=enc.fit_transform(df[['size']])

In [17]:
df.head(7)

     sales          city  size
0   100000         Tampa   0.0
1   222000         Tampa   1.0
2  1000000       Orlando   2.0
3   522000  Jacksonville   2.0
4   111111         Miami   0.0
5   222222  Jacksonville   1.0
6  1111111         Miami   2.0